### ISSUE TITLE
US : superuser access to all tasks

### ISSUE THREAD

**Issue by siobhain** [siobhain/ctb#13]
Part of **EPIC #12**
---

### As an  **admin** I want to...

    **see the list of tasks**

### so that  I can...

     **perform admin actions such as create, read, update, sort, filter and/or delete any task**
---
## Acceptance Criteria 

A Task table with planned fields has been created in the database
View all  tasks via the admin panel & be able to offer CRUD

---
## Tasks needed to complete this User Story (to meet AC above)

- [x] create Task class in models.py
- [x] add Task class to admin panel
- [x] change default str method to return description rather than objects pk
- [x] customise admin panel for ease of use
- [x] add actions to admin panel to offer full CRUD
---
