### ISSUE TITLE
US : View list of  tasks

### ISSUE THREAD

**Issue by siobhain** [siobhain/ctb#16]
Part of **EPIC#**
---
## View the list of tasks sorted by most recent

As a **user**

I can **view the list of task  **

so that  ** I know what current state of play is with the community group **
---
## Acceptance Criteria 

* see the list of tasks on home page
---
## Tasks needed to complete this User Story (to meet AC above)

- [] create the view code
- [] create the template to render the view
- []  connect up the url
---
